name = "The Nexus"
description = "The hub of all admin access"

script = '''
function onEnter(characterID)
  print("someone has entered me")
  narrate(characterID, "hello")
end

function onExit()
  print("someone has left me")
end
'''

[exits]
  # one exit leading west to Rinse's Office.
  [exits.west]
  room_id = 2

  [exits.east]
  room_id = 3
