name = "Arrival Ramp"
region = "Gate Research"
description = """
It feels like you have the worst hangover you've ever experienced. Your head is pounding, your stomach is in knots. Slowly, your senses return to you. Your hearing come first. Muffled sirens become deafening.

A loudspeaker slowly becomes intelligable. "Gate active, incoming arrivals!"

You feel like you might be sick as the room spins around you but, slowly, you get to your feet as you feel hands reach out to help. What were white blurs now start to resolve in to people in lab coats. They wrap you in thermal blankets and thrust a drink bottle in to your hand.

"Take it easy, arrival is nasty business. Drink that, its vitamins and electrolytes. Oh and a mild painkiller, too!" the closest figure says.

As you look more closely, you see the figure helping you up is a dark-haired woman with a namebadge that reads 'Dr. Julia Maggs, Chief Arrivals Officer'.

"Welcome to the new world!" she says, with a wry smile. You feel like she says this a lot and its intended to bring levity to an, otherwise, unpleasant experience. "Don't worry. How you're feeling? That's normal. When you are ready, step down the ramp and follow my colleagues to recovery and orientation."

She leads you to the ramp and goes back to help her colleagues with the other new arrivals. Passed Dr. Maggs, you see... something, hanging in the air, a shimmer like a heat haze over a scorched desert. Looking at it makes your headache even worse and seems to cause a ringing in your ears. You quickly look away and make your way down the ramp.
"""

[exits.north]
room_id = 2 # Entrance
